name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master  # Triggers when code is pushed to master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}  # Unique tag from Git commit hash
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/myapp:$IMAGE_TAG
        LATEST_IMAGE=${{ secrets.DOCKER_USERNAME }}/myapp:latest

        docker build -t $IMAGE_NAME -t $LATEST_IMAGE .
        docker push $IMAGE_NAME
        docker push $LATEST_IMAGE
