name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master  # Runs only when code is pushed to the master branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug Secrets (Check if DOCKER_USERNAME is set)
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "❌ ERROR: DOCKER_USERNAME is empty. Please check your GitHub Secrets."
          exit 1
        fi
        echo "✅ DOCKER_USERNAME is set."

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}  # Short commit SHA as unique tag
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/myapp:$IMAGE_TAG
        LATEST_IMAGE=${{ secrets.DOCKER_USERNAME }}/myapp:latest

        echo "🔹 Using Docker image name: $IMAGE_NAME"
        echo "🔹 Using latest tag: $LATEST_IMAGE"

        docker build -t $IMAGE_NAME -t $LATEST_IMAGE .
        docker push $IMAGE_NAME
        docker push $LATEST_IMAGE

